"""
    WorldTypes

Type definitions for agents and environment structures.
"""
module WorldTypes

using Agents
using ..BrainTypes

export InstitutionAgent, InteractionRecord, GameOutcome

"""
    InteractionRecord

Record of a single interaction from one agent's perspective.

# Fields
- `opponent_label::Bool`: The label of the opponent
- `opponent_cooperated::Bool`: Whether the opponent cooperated
- `own_action::Bool`: Agent's own action (true=cooperate, false=defect)
- `payoff::Float64`: Payoff received from this interaction
"""
@kwdef struct InteractionRecord
    opponent_label::Bool
    opponent_cooperated::Bool
    own_action::Bool
    payoff::Float64
end

"""
    GameOutcome

Possible outcomes of a two-player game.
"""
@enum GameOutcome begin
    MUTUAL_COOPERATION      # Both players cooperate
    EXPLOITATION           # Self cooperates, opponent defects
    BEING_EXPLOITED        # Self defects, opponent cooperates
    MUTUAL_DEFECTION       # Both players defect
end

"""
Determine game outcome from actions.
"""
function get_outcome(own_action::Bool, opponent_action::Bool)::GameOutcome
    if own_action && opponent_action
        return MUTUAL_COOPERATION
    elseif own_action && !opponent_action
        return EXPLOITATION  # Note: from perspective of the one who was exploited
    elseif !own_action && opponent_action
        return BEING_EXPLOITED  # Got exploited
    else
        return MUTUAL_DEFECTION
    end
end

# Fix: correct the naming - if I cooperate and opponent defects, I'm being exploited
function get_outcome_corrected(own_action::Bool, opponent_action::Bool)::GameOutcome
    if own_action && opponent_action
        return MUTUAL_COOPERATION
    elseif own_action && !opponent_action
        return BEING_EXPLOITED  # I cooperated, they defected = I got exploited
    elseif !own_action && opponent_action
        return EXPLOITATION  # I defected, they cooperated = I exploited them
    else
        return MUTUAL_DEFECTION
    end
end

"""
    InstitutionAgent <: AbstractAgent

An agent in the institution emergence simulation.

# Fields
- `id::Int`: Unique agent identifier (auto-generated by Agents.jl)
- `label::Bool`: Binary group label (arbitrary, assigned at birth)
- `cognitive_state::CognitiveState`: Agent's internal cognitive state
- `interaction_history::Vector{InteractionRecord}`: History of past interactions
"""
@agent struct InstitutionAgent(NoSpaceAgent)
    label::Bool
    cognitive_state::CognitiveState
    interaction_history::Vector{InteractionRecord}
end


"""
Check if two agents share the same label (are "ingroup").
"""
function is_ingroup(agent1::InstitutionAgent, agent2::InstitutionAgent)
    return agent1.label == agent2.label
end

"""
Get the number of interactions an agent has had.
"""
function interaction_count(agent::InstitutionAgent)
    return length(agent.interaction_history)
end

"""
Get ingroup interaction history.
"""
function get_ingroup_history(agent::InstitutionAgent)
    filter(r -> r.opponent_label == agent.label, agent.interaction_history)
end

"""
Get outgroup interaction history.
"""
function get_outgroup_history(agent::InstitutionAgent)
    filter(r -> r.opponent_label != agent.label, agent.interaction_history)
end

"""
Calculate empirical cooperation rate from history.
"""
function empirical_cooperation_rate(agent::InstitutionAgent; group::Symbol=:all)
    history = if group == :ingroup
        get_ingroup_history(agent)
    elseif group == :outgroup
        get_outgroup_history(agent)
    else
        agent.interaction_history
    end

    isempty(history) && return 0.5  # Uninformative prior

    n_cooperate = count(r -> r.opponent_cooperated, history)
    return n_cooperate / length(history)
end

"""
Calculate agent's own cooperation rate.
"""
function own_cooperation_rate(agent::InstitutionAgent; group::Symbol=:all)
    history = if group == :ingroup
        get_ingroup_history(agent)
    elseif group == :outgroup
        get_outgroup_history(agent)
    else
        agent.interaction_history
    end

    isempty(history) && return 0.5

    n_cooperate = count(r -> r.own_action, history)
    return n_cooperate / length(history)
end

"""
Calculate average payoff.
"""
function average_payoff(agent::InstitutionAgent)
    isempty(agent.interaction_history) && return 0.0
    sum(r -> r.payoff, agent.interaction_history) / length(agent.interaction_history)
end

end # module
